// ==================== ENCABEZADORES ====================

const vocabularioEncabezadores = {
    // ENCABEZADORES SIN TILDE — material propio (06/10/2026)
    "quien": "https://i.ibb.co/dwdPR7xJ/1.png",
    "que": "https://i.ibb.co/Z6Vz61hg/2.png",
    "porque": "https://i.ibb.co/9ms3mDzK/7.png",
    "cual": "https://i.ibb.co/0R1W3twm/6.png",
    "cuando": "https://i.ibb.co/tp5xccmv/5.png",
    "donde": "https://i.ibb.co/60ncBDx4/4.png",
    "quienes": "https://i.ibb.co/60vgpStW/3.png",
    "por qué": "https://static.arasaac.org/pictograms/36719/36719_300.png",
"quién": "https://i.ibb.co/xKDrXbtt/quien.png",
    "qué": "https://i.ibb.co/N6ByscQZ/que.png",
    "cómo": "https://i.ibb.co/GvWxf1x8/como.png",
    "cómo está": "https://static.arasaac.org/pictograms/10273/10273_300.png",
    "cómo estás": "https://static.arasaac.org/pictograms/10273/10273_300.png",
    "dónde": "https://i.ibb.co/hxqP5p6J/donde.png",
    "cuál": "https://i.ibb.co/sJgqQ7GC/cual.png",
    "cuándo": "https://i.ibb.co/bghT6jnd/cuando.png",
    "cuántos": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "cuántas": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "cuánto": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "cuánta": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "por": "https://i.ibb.co/tMSZ8wKj/por-qu.png",
    "pregunta": "https://i.ibb.co/5gSLP4ht/pregunta.png",
    "quiénes": "https://i.ibb.co/S71JzRkZ/quienes.png",
    "¿por qué": "https://static.arasaac.org/pictograms/36719/36719_300.png",
"¿quién": "https://i.ibb.co/xKDrXbtt/quien.png",
    "¿qué": "https://i.ibb.co/N6ByscQZ/que.png",
    "¿cómo": "https://i.ibb.co/GvWxf1x8/como.png",
    "¿cómo está": "https://static.arasaac.org/pictograms/10273/10273_300.png",
    "¿cómo estás": "https://static.arasaac.org/pictograms/10273/10273_300.png",
    "¿dónde": "https://i.ibb.co/hxqP5p6J/donde.png",
    "¿cuál": "https://i.ibb.co/sJgqQ7GC/cual.png",
    "¿cuándo": "https://i.ibb.co/bghT6jnd/cuando.png",
    "¿cuánto": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "¿cuánta": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "¿cuántos": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "¿cuántas": "https://i.ibb.co/kVpZNSRj/cuantos.png",
    "¿por": "https://i.ibb.co/tMSZ8wKj/por-qu.png",
    "¿pregunta": "https://i.ibb.co/5gSLP4ht/pregunta.png",
    "¿quiénes": "https://i.ibb.co/S71JzRkZ/quienes.png",
    
};

Object.assign(pictogramas, vocabularioEncabezadores);
